In [1]:
import sys
from pathlib import Path
p_temp = str(Path("~/link/csMAHN_publish").expanduser())
None if p_temp in sys.path else sys.path.append(p_temp)
del p_temp

In [2]:
from func import *

2024-11-25 22:02:23.925992: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

[func help]----------------------------------------------------------------
> parameter
    p_root	[name] csMAHN_publish
        p_run, p_plot, p_res, p_cache, p_pdf
    p_df_varmap
    map_sp_reverse
    rng
[from func import * ]------------------------------------------------------
| p_root                  | display              | get_res_obs               |
| p_run                   | h5ad_to_mtx          | get_source_obs            |
| p_plot                  | load_adata           | get_matrix_max_prob_median|
| p_res                   | load_normalized_adata| get_matrix_count          |
| p_cache                 | pdf2_merge           | get_path_varmap           |
| p_pdf                   | show_umap            | get_res_stat              |
| p_data_process          | time_tag_detect      | find_path_from_para       |
| map_sp                  | time_tag_get         | func_help                 |
| map_sp_reverse          | time_tag_toggle      |                           |
| map_sp_SAMap            | get_test_result_df   |                           |
| run_cross_species_models| get_adata_umap       |                           |

[func all name ]-----------------------------------------------------------
| BytesIO                                 | map_sp                       |
| ImageReader                             | map_sp_SAMap                 |
| Iterable                                | map_sp_reverse               |
| Path                                    | mmwrite                      |
| PyPDF2                                  | mpimg                        |
| SAM                                     | mpl                          |
| SAMAP                                   | namedtuple                   |
| StringIO                                | np                           |
| TTFont                                  | os                           |
| ZipFile                                 | p_cache                      |
| aligned_type                            | p_data_process               |
| archive_gzip                            | p_df_varmap                  |
| calculate_F1Score_with_confusion_matrix | p_maps_SAMap                 |
| calculate_accuracy_with_confusion_matrix| p_pdf                        |
| calculate_confusion_matrix              | p_plot                       |
| calculate_more_with_confusion_matrix    | p_res                        |
| calculate_res_stat                      | p_root                       |
| came                                    | p_run                        |
| canvas                                  | palettes                     |
| csMAHN                                  | pd                           |
| csr_matrix                              | pdf2_merge                   |
| customize__init__for_SAMAP              | plt                          |
| customize_calculate_blast_graph         | precess_after_came           |
| df_apply_merge_field                    | precess_after_csMAHN         |
| df_varmap_query_exists                  | re                           |
| display                                 | reportlab                    |
| dumps                                   | rng                          |
| exchange_gn                             | run_cross_species_models     |
| find_path_from_para                     | samap                        |
| get_1v1_matches                         | sana                         |
| get_adata_umap                          | sc                           |
| get_alignment_score_for_each_cell       | show_obj_attr                |
| get_homology_parameters                 | show_str_arr                 |
| get_matrix_count                        | show_umap                    |
| get_matrix_count_ratio                  | sns                          |
| get_matrix_max_prob_median              | sp                           |
| get_path_varmap                         | stats                        |
| get_res_obs                             | subset_adata                 |
| get_res_stat                            | tarfile                      |
| get_source_obs                          | time                         |
| get_test_result_df                      | time_tag_detect              |
| get_type_counts_info                    | time_tag_get                 |
| group_agg                               | time_tag_toggle              |
| h5ad_to_mtx                             | typing                       |
| is_1v1                                  | unify_group_counts_index_name|
| load_adata                              | warnings                     |
| load_normalized_adata                   | zip_longest                  |
| loads                                   |                              |
| map_func_run_cross_species_models       |                              |

In [3]:
import utils as ut
from utils.general import *

In [4]:
# q_tissue = "Adrenal-Gland,Bone-Marrow,Brain,Heart,Intestine,Kidney,Liver,Lung,Spleen".split(',')
# data = get_test_result_df(p_res).query("tissue in @q_tissue").reset_index(drop=True)
# data['F1-score'] = data.apply(get_res_stat, key='F1-score',
#                               q="dataset_type == 'que'", axis=1)
# data['Accuracy'] = data.apply(get_res_stat, key='Accuracy',
#                               q="dataset_type == 'que'", axis=1)
# data

# row = data.iloc[119,:]
# get_res_obs(row)

In [5]:
data = get_test_result_df(Path("~/link/other_model/learn_TOSICA").expanduser())
row = data.iloc[0,:]

get_res_obs(row)

,UMAP1,UMAP2,cell_type,dataset,is_right,max_prob,pre_label,true_label,dataset_type,sp
bcAGGC;h1tl_1,1.564831,6.272377,MonoDC,LC_h,False,0.486587,DC2,MonoDC,ref,h
bcGDSJ;h1tl_1,0.592450,8.898167,DC2,LC_h,True,0.548159,DC2,DC2,ref,h
bcEZQB;h1tl_1,3.795469,9.308646,MonoDC,LC_h,True,0.581997,MonoDC,MonoDC,ref,h
bcBUMT;h1tl_1,3.855231,7.879448,MonoDC,LC_h,True,0.654899,MonoDC,MonoDC,ref,h
bcEPPT;h1tl_1,1.809484,8.547212,MonoDC,LC_h,True,0.477193,MonoDC,MonoDC,ref,h
...,...,...,...,...,...,...,...,...,...,...
bc0719;m2tl_4,5.737757,5.132926,DC1,LC_m,False,0.725167,DC3,DC1,que,m
bc0806;m2tl_4,7.971606,5.180623,MonoDC,LC_m,False,0.708843,pDC,MonoDC,que,m
bc0859;m2tl_4,5.101405,3.765846,DC3,LC_m,True,0.816139,DC3,DC3,que,m
bc0950;m2tl_4,6.719289,5.939974,pDC,LC_m,False,0.638844,MonoDC,pDC,que,m
bc1062;m2tl_4,5.478564,4.278084,DC3,LC_m,True,0.776172,DC3,DC3,que,m

In [6]:
data['F1-score'] = data.apply(get_res_stat, key='F1-score',
                              q="dataset_type == 'que'", axis=1)
data['Accuracy'] = data.apply(get_res_stat, key='Accuracy',
                              q="dataset_type == 'que'", axis=1)
data

,dir,name,tissue,sp_ref,sp_que,model,name_ref,name_que,resdir_tag,F1-score,Accuracy
4,/public/workspace/licanchengup/link/other_mode...,LC_h-corss-m;TOSICA;LChDCs-map-LCmDCs;is_1v1=True,LC,h,m,TOSICA,LChDCs,LCmDCs,is_1v1=True,0.516292,0.517028